### PR TITLE
1.7.10 file and webbrowser support for Linux/Unix

### PR DESCRIPTION
**Pull request by Keridos**
Fixing a crash on Linux when file browsing because the Browse Action could be unsupported.
Added in an easily expandable support for opening file locations and weblinks in the appropriate application if found on the system. Got the base for that from here but modified it quite a bit: http://www.centerkey.com/java/browser/

Also made gradlew executable on Linux.

This should be merge-able into the main branch as well, if you like to use it.

### CODE REVIEW

**Comment by Keridos** [comment]
Also fixes #67

**Comment by Keridos** [comment]
Also fixes #67

**Comment by Dynious** [comment]
Thanks a lot, I have no Linux machine to test this so this helps a lot :D One thing, could you change the bracket style to the one used in this project?

**Comment by Keridos** [comment]
Done!

**Pull request merged**
